language: node_js

node_js:
  - v7

env:
  global:
  matrix:
    - TRAVIS_MATRIX=test
    - TRAVIS_MATRIX=build
    - TRAVIS_MATRIX=build.demo

script:
  - npm run $TRAVIS_MATRIX

after_success:
  - node scripts/deploy
