language: node_js

node_js:
  - v8

env:
  global:
  matrix:
    - TRAVIS_MATRIX=test
    - TRAVIS_MATRIX=build:page
    - TRAVIS_MATRIX=build:lib

script:
  - npm run $TRAVIS_MATRIX

after_success:
  - node scripts/deploy

branches:
  except:
    - /^v?\d+\.\d+\.\d+/
